# Generated by Django 5.2.17 on 2026-08-24 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('blocklist_type', models.CharField(max_length=50)),
                ('severity_filter', models.CharField(max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('indicator_count', models.IntegerField(default=0)),
                ('file_format', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=100)),
                ('feed_type', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('normalized_value', models.TextField(db_index=True, unique=True)),
                ('ioc_type', models.CharField(max_length=50)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('severity', models.CharField(default='Low', max_length=50)),
                ('risk_score', models.IntegerField(default=0)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('module', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CorrelationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_count', models.IntegerField(default=0)),
                ('occurrence_count', models.IntegerField(default=0)),
                ('risk_score', models.IntegerField(default=0)),
                ('severity', models.CharField(default='Low', max_length=50)),
                ('reason', models.TextField(blank=True)),
                ('correlated_at', models.DateTimeField(auto_now=True)),
                ('ioc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlation_results', to='aggregator.ioc')),
            ],
        ),
        migrations.CreateModel(
            name='IOCSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('occurrence_count', models.IntegerField(default=1)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iocs', to='aggregator.feed')),
                ('ioc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='aggregator.ioc')),
            ],
            options={
                'unique_together': {('ioc', 'feed')},
            },
        ),
    ]
