# Generated by Django 5.2.17 on 2026-09-03 05:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0002_vulnerability_alter_activitylog_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='activitylog',
            name='activity_module_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='activitylog',
            name='activity_user_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='correlationresult',
            name='corr_severity_risk_idx',
        ),
        migrations.RemoveIndex(
            model_name='iocsource',
            name='iocsource_feed_seen_idx',
        ),
        migrations.RemoveIndex(
            model_name='iocsource',
            name='iocsource_ioc_seen_idx',
        ),
        migrations.RenameIndex(
            model_name='feed',
            new_name='aggregator__is_acti_33fc8b_idx',
            old_name='feed_active_category_idx',
        ),
        migrations.RenameIndex(
            model_name='feed',
            new_name='aggregator__source_5c6f91_idx',
            old_name='feed_source_type_idx',
        ),
        migrations.RenameIndex(
            model_name='ioc',
            new_name='aggregator__ioc_typ_b2f30b_idx',
            old_name='ioc_type_severity_idx',
        ),
        migrations.RenameIndex(
            model_name='ioc',
            new_name='aggregator__status_c952f3_idx',
            old_name='ioc_status_risk_idx',
        ),
        migrations.RenameIndex(
            model_name='vulnerability',
            new_name='aggregator__vendor_b1f65d_idx',
            old_name='vuln_vendor_product_idx',
        ),
        migrations.RenameIndex(
            model_name='vulnerability',
            new_name='aggregator__date_ad_e75b12_idx',
            old_name='vuln_date_added_idx',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='module',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='status',
            field=models.CharField(choices=[('Success', 'Success'), ('Error', 'Error'), ('Warning', 'Warning'), ('Info', 'Info')], max_length=50),
        ),
        migrations.AlterField(
            model_name='blocklist',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='correlationresult',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='correlationresult',
            name='risk_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='correlationresult',
            name='severity',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Low', max_length=50),
        ),
        migrations.AlterField(
            model_name='feed',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ioc',
            name='risk_score',
            field=models.IntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='known_ransomware_use',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='product',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='vendor',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
