# Generated by Django 5.2.17 on 2026-09-29 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0003_remove_activitylog_activity_module_status_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ioc',
            name='ioc_type',
            field=models.CharField(choices=[('IPv4', 'IPv4'), ('IPv6', 'IPv6'), ('Domain', 'Domain'), ('URL', 'URL'), ('Hash', 'Hash'), ('Email', 'Email')], db_index=True, max_length=50),
        ),
    ]
